#!/bin/sh
################################################################################
# Aria2 Init Script
# - Loads RPC secret from shared-keys volume
# - Resolves ntfy IP at startup via Docker's embedded DNS (127.0.0.11),
#   bypassing gluetun's DNS override (1.1.1.1 via VPN)
# - Writes notification hooks to /config/ at runtime (like pyload-init.sh)
#   with the resolved IP baked in; each hook also re-resolves on every call
#   so ntfy container restarts don't require aria2 restart
# - Categories work via /media mount: set "dir" per download in AriaNg
################################################################################

set -eu

CONFIG_DIR="/config"
ARIA_CONF="${CONFIG_DIR}/aria2.conf"
RPC_PORT="${RPC_PORT:-6800}"
LISTEN_PORT="${LISTEN_PORT:-6888}"

# Download tuning (all configurable via env)
ARIA2_MAX_CONCURRENT="${ARIA2_MAX_CONCURRENT:-5}"
ARIA2_MAX_CONN_PER_SERVER="${ARIA2_MAX_CONN_PER_SERVER:-16}"
ARIA2_SPLIT="${ARIA2_SPLIT:-16}"
ARIA2_MIN_SPLIT_SIZE="${ARIA2_MIN_SPLIT_SIZE:-1M}"
ARIA2_DISK_CACHE="${ARIA2_DISK_CACHE:-${DISK_CACHE:-64M}}"
ARIA2_FILE_ALLOC="${ARIA2_FILE_ALLOC:-none}"
ARIA2_MAX_TRIES="${ARIA2_MAX_TRIES:-5}"
ARIA2_RETRY_WAIT="${ARIA2_RETRY_WAIT:-5}"
ARIA2_MAX_DL_LIMIT="${ARIA2_MAX_DL_LIMIT:-0}"
ARIA2_MAX_UL_LIMIT="${ARIA2_MAX_UL_LIMIT:-0}"

# BitTorrent tuning
ARIA2_BT_MAX_PEERS="${ARIA2_BT_MAX_PEERS:-55}"
ARIA2_SEED_RATIO="${ARIA2_SEED_RATIO:-1.0}"
ARIA2_SEED_TIME="${ARIA2_SEED_TIME:-0}"

# Ntfy
NTFY_INTERNAL_URL="${NTFY_INTERNAL_URL:-http://ntfy:80}"
NTFY_TOPIC="${NTFY_TOPIC:-potatostack}"
NTFY_TOKEN="${NTFY_TOKEN:-}"

echo "╔══════════════════════════════════════════════════════════════════╗"
echo "║                       Aria2 Init Script                          ║"
echo "╚══════════════════════════════════════════════════════════════════╝"

mkdir -p "$CONFIG_DIR"

################################################################################
# RPC Secret
################################################################################
if [ -f "/keys/aria2-rpc-secret" ]; then
	ARIA2_RPC_SECRET=$(cat /keys/aria2-rpc-secret)
	echo "✓ Loaded RPC secret from shared volume"
else
	echo "⚠ RPC secret not found at /keys/aria2-rpc-secret"
	if [ -z "${RPC_SECRET:-}" ]; then
		ARIA2_RPC_SECRET=$(head -c 32 /dev/urandom | hexdump -ve '1/1 "%.2x"' | tr -d '\n')
		echo "✓ Generated temporary RPC secret"
	else
		ARIA2_RPC_SECRET="$RPC_SECRET"
		echo "✓ Using RPC_SECRET from environment"
	fi
fi

# Write to s6 environment so aria2-pro's service scripts also see it
mkdir -p /var/run/s6/container_environment
printf '%s' "$ARIA2_RPC_SECRET" >/var/run/s6/container_environment/RPC_SECRET

################################################################################
# Resolve ntfy IP
# Gluetun replaces resolv.conf (→ 1.1.1.1 via VPN), but Docker's embedded DNS
# listener at 127.0.0.11 remains active in the network namespace.
# Querying it directly bypasses gluetun's DNS override.
################################################################################
resolve_ntfy_ip() {
	# Extract all IPv4 addresses from nslookup output, skip the DNS server itself
	nslookup ntfy 127.0.0.11 2>/dev/null \
		| tr ' \t' '\n' \
		| grep -E '^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$' \
		| grep -v '127\.0\.0\.11' \
		| head -1 || true
}

NTFY_RESOLVED_IP=$(resolve_ntfy_ip)
if [ -n "$NTFY_RESOLVED_IP" ]; then
	NTFY_EFFECTIVE_URL="http://${NTFY_RESOLVED_IP}:80"
	echo "✓ ntfy resolved via 127.0.0.11: ${NTFY_RESOLVED_IP}"
else
	NTFY_EFFECTIVE_URL="$NTFY_INTERNAL_URL"
	echo "⚠ ntfy not resolvable via 127.0.0.11; falling back to: ${NTFY_EFFECTIVE_URL}"
	echo "  Notifications may fail behind gluetun until ntfy IP is set in NTFY_INTERNAL_URL"
fi

################################################################################
# Write notification hook scripts at runtime (pyload-init.sh pattern)
# Variables expanded NOW (baked in): NTFY_EFFECTIVE_URL, NTFY_TOPIC, NTFY_TOKEN
# Variables escaped (\$): runtime args and re-resolve logic inside the hooks
# Each hook re-resolves ntfy IP on every call → survives ntfy container restarts
################################################################################
########################################################################
# on-download-complete: handles HTTP/direct downloads.
# aria2 downloads to /incomplete; move to /downloads when done so
# unpackerr only ever sees fully-completed files.
#
# For BT multi-file downloads aria2 also fires on-download-complete for
# each individual file — those files live inside a subdirectory of
# /incomplete. Skip them here; on-bt-download-complete handles the move
# for the whole torrent directory once seeding criteria are met.
########################################################################
cat >"${CONFIG_DIR}/aria2-on-complete.sh" <<EOF
#!/bin/sh
# Auto-generated by aria2-init.sh — DO NOT EDIT (overwritten on aria2 restart)
GID="\${1:-}"
SRC="\${3:-}"
LOG_FILE="${CONFIG_DIR}/aria2-notifications.log"
NTFY_TOPIC="${NTFY_TOPIC}"
NTFY_TOKEN="${NTFY_TOKEN}"

# Skip BT per-file callbacks: those paths are inside a subdirectory of
# /incomplete (e.g. /incomplete/TorrentName/file.mkv). The BT-complete
# hook handles moving the whole directory when the torrent is done.
if [ -n "\$SRC" ] && [ "\$(dirname "\$SRC")" != "/incomplete" ]; then
  exit 0
fi

# Move completed file from /incomplete to /downloads (same fs = instant rename)
FINAL_PATH="\$SRC"
if [ -n "\$SRC" ] && [ -e "\$SRC" ]; then
  DEST="/downloads/\$(basename "\$SRC")"
  if mv -f "\$SRC" "\$DEST" 2>/dev/null; then
    printf '[%s] moved: %s -> %s\n' "\$(date +'%Y-%m-%d %H:%M:%S')" "\$SRC" "\$DEST" >>"\$LOG_FILE"
    FINAL_PATH="\$DEST"
  else
    printf '[%s] move-failed: %s\n' "\$(date +'%Y-%m-%d %H:%M:%S')" "\$SRC" >>"\$LOG_FILE"
  fi
fi

FILE_NAME=\$(basename "\${FINAL_PATH:-unknown}")
printf '[%s] complete: GID=%s path=%s\n' "\$(date +'%Y-%m-%d %H:%M:%S')" "\$GID" "\$FINAL_PATH" >>"\$LOG_FILE"

# Re-resolve ntfy IP on each call (survives ntfy container restarts)
_ip=\$(nslookup ntfy 127.0.0.11 2>/dev/null | tr ' \t' '\n' | grep -E '^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\$' | grep -v '127\.0\.0\.11' | head -1 || true)
NTFY_URL=\${_ip:+http://\${_ip}:80}
NTFY_URL=\${NTFY_URL:-${NTFY_EFFECTIVE_URL}}

if command -v curl >/dev/null 2>&1; then
  if [ -n "\$NTFY_TOKEN" ]; then
    curl -fsS -X POST "\${NTFY_URL}/\${NTFY_TOPIC}" \
      -H "Title: Download Complete" -H "Tags: white_check_mark,aria2" -H "Priority: low" \
      -H "Authorization: Bearer \${NTFY_TOKEN}" \
      -d "\${FILE_NAME}" >>\$LOG_FILE 2>&1 || true
  else
    curl -fsS -X POST "\${NTFY_URL}/\${NTFY_TOPIC}" \
      -H "Title: Download Complete" -H "Tags: white_check_mark,aria2" -H "Priority: low" \
      -d "\${FILE_NAME}" >>\$LOG_FILE 2>&1 || true
  fi
fi
EOF

########################################################################
# on-bt-download-complete: called once when an entire BitTorrent
# download finishes (seeding criteria met). Moves the top-level
# directory or single-file torrent from /incomplete to /downloads.
########################################################################
cat >"${CONFIG_DIR}/aria2-on-bt-complete.sh" <<EOF
#!/bin/sh
# Auto-generated by aria2-init.sh — DO NOT EDIT (overwritten on aria2 restart)
GID="\${1:-}"
SRC="\${3:-}"
LOG_FILE="${CONFIG_DIR}/aria2-notifications.log"
NTFY_TOPIC="${NTFY_TOPIC}"
NTFY_TOKEN="${NTFY_TOKEN}"

# Resolve the top-level item under /incomplete
# Single-file torrent: SRC = /incomplete/file.rar     → top = /incomplete/file.rar
# Multi-file torrent:  SRC = /incomplete/Name/a.mkv   → top = /incomplete/Name
MOVE_SRC=""
if [ -n "\$SRC" ]; then
  case "\$SRC" in
    /incomplete/*)
      REL="\${SRC#/incomplete/}"          # strip leading /incomplete/
      TOPNAME="\${REL%%/*}"               # first path component
      MOVE_SRC="/incomplete/\${TOPNAME}"
      ;;
  esac
fi

FINAL_PATH="\$SRC"
if [ -n "\$MOVE_SRC" ] && [ -e "\$MOVE_SRC" ]; then
  DEST="/downloads/\$(basename "\$MOVE_SRC")"
  if mv -f "\$MOVE_SRC" "\$DEST" 2>/dev/null; then
    printf '[%s] bt-moved: %s -> %s\n' "\$(date +'%Y-%m-%d %H:%M:%S')" "\$MOVE_SRC" "\$DEST" >>"\$LOG_FILE"
    FINAL_PATH="\$DEST"
  else
    printf '[%s] bt-move-failed: %s\n' "\$(date +'%Y-%m-%d %H:%M:%S')" "\$MOVE_SRC" >>"\$LOG_FILE"
  fi
fi

FILE_NAME=\$(basename "\${FINAL_PATH:-unknown}")
printf '[%s] bt-complete: GID=%s path=%s\n' "\$(date +'%Y-%m-%d %H:%M:%S')" "\$GID" "\$FINAL_PATH" >>"\$LOG_FILE"

_ip=\$(nslookup ntfy 127.0.0.11 2>/dev/null | tr ' \t' '\n' | grep -E '^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\$' | grep -v '127\.0\.0\.11' | head -1 || true)
NTFY_URL=\${_ip:+http://\${_ip}:80}
NTFY_URL=\${NTFY_URL:-${NTFY_EFFECTIVE_URL}}

if command -v curl >/dev/null 2>&1; then
  if [ -n "\$NTFY_TOKEN" ]; then
    curl -fsS -X POST "\${NTFY_URL}/\${NTFY_TOPIC}" \
      -H "Title: Torrent Complete" -H "Tags: white_check_mark,aria2" -H "Priority: low" \
      -H "Authorization: Bearer \${NTFY_TOKEN}" \
      -d "\${FILE_NAME}" >>\$LOG_FILE 2>&1 || true
  else
    curl -fsS -X POST "\${NTFY_URL}/\${NTFY_TOPIC}" \
      -H "Title: Torrent Complete" -H "Tags: white_check_mark,aria2" -H "Priority: low" \
      -d "\${FILE_NAME}" >>\$LOG_FILE 2>&1 || true
  fi
fi
EOF

cat >"${CONFIG_DIR}/aria2-on-error.sh" <<EOF
#!/bin/sh
# Auto-generated by aria2-init.sh — DO NOT EDIT (overwritten on aria2 restart)
GID="\${1:-}"
FILE_PATH="\${3:-}"
FILE_NAME=\$(basename "\${FILE_PATH:-unknown}")
LOG_FILE="${CONFIG_DIR}/aria2-notifications.log"
NTFY_TOPIC="${NTFY_TOPIC}"
NTFY_TOKEN="${NTFY_TOKEN}"

_ip=\$(nslookup ntfy 127.0.0.11 2>/dev/null | tr ' \t' '\n' | grep -E '^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\$' | grep -v '127\.0\.0\.11' | head -1 || true)
NTFY_URL=\${_ip:+http://\${_ip}:80}
NTFY_URL=\${NTFY_URL:-${NTFY_EFFECTIVE_URL}}

printf '[%s] error: GID=%s path=%s\n' "\$(date +'%Y-%m-%d %H:%M:%S')" "\$GID" "\$FILE_PATH" >>"\$LOG_FILE"

if command -v curl >/dev/null 2>&1; then
  if [ -n "\$NTFY_TOKEN" ]; then
    curl -fsS -X POST "\${NTFY_URL}/\${NTFY_TOPIC}" \
      -H "Title: Download Error" -H "Tags: x,aria2" -H "Priority: high" \
      -H "Authorization: Bearer \${NTFY_TOKEN}" \
      -d "\${FILE_NAME:-unknown}" >>\$LOG_FILE 2>&1 || true
  else
    curl -fsS -X POST "\${NTFY_URL}/\${NTFY_TOPIC}" \
      -H "Title: Download Error" -H "Tags: x,aria2" -H "Priority: high" \
      -d "\${FILE_NAME:-unknown}" >>\$LOG_FILE 2>&1 || true
  fi
fi
EOF

chmod +x "${CONFIG_DIR}/aria2-on-complete.sh" "${CONFIG_DIR}/aria2-on-bt-complete.sh" "${CONFIG_DIR}/aria2-on-error.sh"

# s6's 58-permissions script will reset /config/*.sh to 0600 (non-executable).
# Inject a cont-init.d script at 89 (runs after 58-permissions) to restore +x.
cat >/etc/cont-init.d/89-aria2-hooks <<'INITEOF'
#!/bin/sh
chmod +x /config/aria2-on-complete.sh /config/aria2-on-bt-complete.sh /config/aria2-on-error.sh 2>/dev/null || true
INITEOF
chmod +x /etc/cont-init.d/89-aria2-hooks

# p3terx/aria2-pro's 28-fix script forces dir=/downloads after our aria2.conf is written.
# Inject a 29-dir-override to restore dir=/incomplete immediately after 28-fix.
cat >/etc/cont-init.d/29-dir-override <<'INITEOF'
#!/bin/sh
ARIA2_CONF="${ARIA2_CONF:-/config/aria2.conf}"
sed -i "s@^\(dir=\).*@\1/incomplete@" "${ARIA2_CONF}"
INITEOF
chmod +x /etc/cont-init.d/29-dir-override

echo "✓ Notification hooks written (ntfy=${NTFY_EFFECTIVE_URL}, re-resolves each call)"

################################################################################
# Session file
################################################################################
touch "${CONFIG_DIR}/aria2.session"

################################################################################
# aria2.conf
################################################################################
cat >"$ARIA_CONF" <<EOF
# Aria2 Configuration — PotatoStack
# Generated: $(date)
# AriaNg RPC setup: Protocol=WebSocket  Host=potatostack.tale-iwato.ts.net  Port=${RPC_PORT}  Path=/jsonrpc

disable-ipv6=true

# RPC
enable-rpc=true
rpc-listen-all=true
rpc-allow-origin-all=true
rpc-listen-port=${RPC_PORT}
rpc-secret=${ARIA2_RPC_SECRET}

# Paths
dir=/incomplete
input-file=${CONFIG_DIR}/aria2.session
save-session=${CONFIG_DIR}/aria2.session
save-session-interval=60
log=${CONFIG_DIR}/aria2.log
log-level=warn

# Downloads
max-concurrent-downloads=${ARIA2_MAX_CONCURRENT}
max-connection-per-server=${ARIA2_MAX_CONN_PER_SERVER}
min-split-size=${ARIA2_MIN_SPLIT_SIZE}
split=${ARIA2_SPLIT}
max-tries=${ARIA2_MAX_TRIES}
retry-wait=${ARIA2_RETRY_WAIT}
max-download-limit=${ARIA2_MAX_DL_LIMIT}
max-upload-limit=${ARIA2_MAX_UL_LIMIT}
continue=true
force-save=true

# Disk
file-allocation=${ARIA2_FILE_ALLOC}
disk-cache=${ARIA2_DISK_CACHE}

# BitTorrent
listen-port=${LISTEN_PORT}
dht-listen-port=${LISTEN_PORT}
bt-enable-lpd=true
bt-max-peers=${ARIA2_BT_MAX_PEERS}
seed-ratio=${ARIA2_SEED_RATIO}
seed-time=${ARIA2_SEED_TIME}

# Hooks
on-download-complete=${CONFIG_DIR}/aria2-on-complete.sh
on-bt-download-complete=${CONFIG_DIR}/aria2-on-bt-complete.sh
on-download-error=${CONFIG_DIR}/aria2-on-error.sh
EOF

echo "✓ aria2.conf written"
echo ""
echo "  RPC secret (first 16 chars): ${ARIA2_RPC_SECRET:0:16}..."
echo ""
echo "  Category dirs — set 'dir' per download in AriaNg:"
echo "    /media/movies   /media/tv      /media/music"
echo "    /media/audiobooks  /media/books   /downloads (default)"
echo ""

exec /init "$@"
