#!/bin/sh
################################################################################
# AriaNg Init Script
# Runs on every container start (nginx:alpine).
# - Downloads latest AriaNg from GitHub releases (fallback: bundled static files)
# - Reads aria2 RPC secret from shared-keys volume
# - Generates rpc-config.js with current secret and RPC endpoint
# - Injects <script src="rpc-config.js"> into index.html
# - Starts nginx
# Result: always runs the latest AriaNg, auto-configured on every browser/device.
################################################################################

set -eu

STATIC_FALLBACK="/AriaNg-static"
HTML_DIR="/usr/share/nginx/html"
RPC_HOST="${ARIANG_RPC_HOST}"
RPC_PORT="${ARIANG_RPC_PORT:-6800}"

echo "╔══════════════════════════════════════════════════════════════════╗"
echo "║                      AriaNg Init Script                          ║"
echo "╚══════════════════════════════════════════════════════════════════╝"

################################################################################
# Read RPC secret (same source as aria2-init.sh)
################################################################################
if [ -f "/keys/aria2-rpc-secret" ]; then
	RPC_SECRET=$(cat /keys/aria2-rpc-secret)
	echo "✓ Loaded RPC secret from shared volume"
else
	RPC_SECRET="${ARIA2_RPC_SECRET:-}"
	echo "⚠ /keys/aria2-rpc-secret not found, using ARIA2_RPC_SECRET env var"
fi

################################################################################
# Download latest AriaNg from GitHub releases.
# Falls back to bundled static files if GitHub is unreachable.
# Uses apk to install unzip (fast on Alpine, ~200ms).
################################################################################
_fetch_ariang() {
	apk add -q --no-cache unzip 2>/dev/null || return 1
	echo "Fetching latest AriaNg release info..."
	API_JSON=$(wget -qO- -T 10 "https://api.github.com/repos/mayswind/AriaNg/releases/latest" 2>/dev/null) || return 1
	ZIP_URL=$(printf '%s\n' "$API_JSON" \
		| grep '"browser_download_url"' \
		| grep -v 'AllInOne' \
		| grep '\.zip' \
		| head -1 \
		| cut -d'"' -f4)
	[ -n "$ZIP_URL" ] || return 1
	echo "Downloading $(basename "$ZIP_URL")..."
	wget -qO /tmp/ariang.zip -T 30 "$ZIP_URL" 2>/dev/null || return 1
	rm -rf "${HTML_DIR:?}"/*
	unzip -q /tmp/ariang.zip -d "$HTML_DIR" || return 1
	rm -f /tmp/ariang.zip
	VERSION=$(printf '%s\n' "$API_JSON" | grep '"tag_name"' | head -1 | cut -d'"' -f4)
	echo "✓ AriaNg ${VERSION} downloaded from GitHub"
}

if _fetch_ariang; then
	:
else
	echo "⚠ GitHub unavailable, using bundled fallback files"
	cp -r "${STATIC_FALLBACK}/." "${HTML_DIR}/"
fi

################################################################################
# Write custom nginx config:
# - SPA fallback: try_files so hard-refreshing any route serves index.html
# - No-cache for rpc-config.js so browsers always get the latest secret/host
################################################################################
cat >/etc/nginx/conf.d/default.conf <<'NGINXCONF'
server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # rpc-config.*.js is versioned per-restart — no-cache for index.html too
    location ~* ^/rpc-config\..+\.js$ {
        add_header Cache-Control "no-store, no-cache, must-revalidate";
        expires -1;
    }

    location = /index.html {
        add_header Cache-Control "no-store, no-cache, must-revalidate";
        expires -1;
    }

    # SPA fallback: serve index.html for any unmatched path
    location / {
        try_files $uri $uri/ /index.html;
    }
}
NGINXCONF
echo "✓ nginx config written (no-cache rpc-config.js, SPA fallback)"

################################################################################
# Generate rpc-config.js — overwrites on every container restart so the secret
# stays in sync if aria2 is recreated.
# Sets localStorage["AriaNg.Options"] unconditionally so any browser/device
# opening the URL gets the correct RPC settings without manual configuration.
################################################################################
# AriaNg 1.3.x stores the primary RPC endpoint as FLAT top-level fields in localStorage
# (NOT in a rpcSettings array — that is built at runtime from these flat fields).
# The secret is stored base64-encoded and decoded on read.
# language must be "" (not undefined) or the language-lookup function h() crashes.
RPC_SECRET_B64=$(printf '%s' "${RPC_SECRET}" | base64 | tr -d '\n')

# Use a content hash so browsers never serve a cached old version
RPC_HASH=$(printf '%s%s%s%s' "${RPC_HOST}" "${RPC_PORT}" "${RPC_SECRET}" "v3-flat" | md5sum | cut -c1-8)
RPC_JS="rpc-config.${RPC_HASH}.js"

cat >"${HTML_DIR}/${RPC_JS}" <<EOF
/* Auto-generated by ariang-init.sh — do not edit, overwritten on restart */
(function () {
  var k = 'AriaNg.Options';

  /* AriaNg 1.3.x: primary RPC uses flat top-level fields, NOT rpcSettings[].
     language must be "" (not undefined) — h(undefined).toLowerCase() crashes Angular init.
     secret is stored base64-encoded (AriaNg decodes it on every read).
     protocol "https" → HTTPS POST to Tailscale-served port 6800, no mixed-content issue. */
  localStorage.removeItem(k);
  localStorage.setItem(k, JSON.stringify({
    initialized:               true,
    language:                  "",
    rpcAlias:                  "",
    rpcHost:                   "${RPC_HOST}",
    rpcPort:                   "${RPC_PORT}",
    rpcInterface:              "jsonrpc",
    protocol:                  "https",
    httpMethod:                "POST",
    rpcRequestHeaders:         "",
    secret:                    "${RPC_SECRET_B64}",
    extendRpcServers:          [],
    webSocketReconnectInterval: 5000
  }));
  console.log('[ariang-init] rpc-config applied: https://${RPC_HOST}:${RPC_PORT}/jsonrpc');
})();
EOF
echo "✓ rpc-config.js generated (host=${RPC_HOST}:${RPC_PORT}, protocol=https, hash=${RPC_HASH})"

################################################################################
# Inject <script src="rpc-config.<hash>.js"> into index.html before </head>
# Versioned filename busts browser cache — browser always loads fresh config.
# Must run BEFORE Angular bootstraps so localStorage is set when app loads.
################################################################################
sed -i "s|</head>|<script src=\"${RPC_JS}\"></script></head>|" "${HTML_DIR}/index.html"
echo "✓ ${RPC_JS} injected into index.html"

echo ""
echo "  Open: https://${RPC_HOST}:6880"
echo "  aria2 RPC: wss://${RPC_HOST}:${RPC_PORT}/jsonrpc"
echo "  Secret: ${RPC_SECRET:0:16}..."
echo ""

exec nginx -g "daemon off;"
