#!/bin/sh
################################################################################
# AriaNg Init Script
# Runs on every container start (nginx:alpine).
# - Downloads latest AriaNg from GitHub releases (fallback: bundled static files)
# - Reads aria2 RPC secret from shared-keys volume
# - Generates rpc-config.js with current secret and RPC endpoint
# - Injects <script src="rpc-config.js"> into index.html
# - Starts nginx
# Result: always runs the latest AriaNg, auto-configured on every browser/device.
################################################################################

set -eu

STATIC_FALLBACK="/AriaNg-static"
HTML_DIR="/usr/share/nginx/html"
RPC_HOST="${ARIANG_RPC_HOST}"
RPC_PORT="${ARIANG_RPC_PORT:-6800}"

echo "╔══════════════════════════════════════════════════════════════════╗"
echo "║                      AriaNg Init Script                          ║"
echo "╚══════════════════════════════════════════════════════════════════╝"

################################################################################
# Read RPC secret (same source as aria2-init.sh)
################################################################################
if [ -f "/keys/aria2-rpc-secret" ]; then
	RPC_SECRET=$(cat /keys/aria2-rpc-secret)
	echo "✓ Loaded RPC secret from shared volume"
else
	RPC_SECRET="${ARIA2_RPC_SECRET:-}"
	echo "⚠ /keys/aria2-rpc-secret not found, using ARIA2_RPC_SECRET env var"
fi

################################################################################
# Download latest AriaNg from GitHub releases.
# Falls back to bundled static files if GitHub is unreachable.
# Uses apk to install unzip (fast on Alpine, ~200ms).
################################################################################
_fetch_ariang() {
	apk add -q --no-cache unzip 2>/dev/null || return 1
	echo "Fetching latest AriaNg release info..."
	API_JSON=$(wget -qO- -T 10 "https://api.github.com/repos/mayswind/AriaNg/releases/latest" 2>/dev/null) || return 1
	ZIP_URL=$(printf '%s\n' "$API_JSON" \
		| grep '"browser_download_url"' \
		| grep -v 'AllInOne' \
		| grep '\.zip' \
		| head -1 \
		| cut -d'"' -f4)
	[ -n "$ZIP_URL" ] || return 1
	echo "Downloading $(basename "$ZIP_URL")..."
	wget -qO /tmp/ariang.zip -T 30 "$ZIP_URL" 2>/dev/null || return 1
	rm -rf "${HTML_DIR:?}"/*
	unzip -q /tmp/ariang.zip -d "$HTML_DIR" || return 1
	rm -f /tmp/ariang.zip
	VERSION=$(printf '%s\n' "$API_JSON" | grep '"tag_name"' | head -1 | cut -d'"' -f4)
	echo "✓ AriaNg ${VERSION} downloaded from GitHub"
}

if _fetch_ariang; then
	:
else
	echo "⚠ GitHub unavailable, using bundled fallback files"
	cp -r "${STATIC_FALLBACK}/." "${HTML_DIR}/"
fi

################################################################################
# Generate rpc-config.js — overwrites on every container restart so the secret
# stays in sync if aria2 is recreated.
# Sets localStorage["AriaNg.Options"] unconditionally so any browser/device
# opening the URL gets the correct RPC settings without manual configuration.
################################################################################
cat >"${HTML_DIR}/rpc-config.js" <<EOF
/* Auto-generated by ariang-init.sh — do not edit, overwritten on restart */
(function () {
  var k = 'AriaNg.Options';
  var opts;
  try { opts = JSON.parse(localStorage.getItem(k) || '{}'); } catch (e) { opts = {}; }
  opts.rpcHost     = "${RPC_HOST}";
  opts.rpcPort     = "${RPC_PORT}";
  opts.rpcInterface = "jsonrpc";
  opts.protocol    = "wss";
  opts.secret      = "${RPC_SECRET}";
  localStorage.setItem(k, JSON.stringify(opts));
})();
EOF
echo "✓ rpc-config.js generated (host=${RPC_HOST}:${RPC_PORT}, protocol=wss)"

################################################################################
# Inject <script src="rpc-config.js"> into index.html before </head>
# Must run BEFORE Angular bootstraps so localStorage is set when app loads.
################################################################################
sed -i 's|</head>|<script src="rpc-config.js"></script></head>|' "${HTML_DIR}/index.html"
echo "✓ rpc-config.js injected into index.html"

echo ""
echo "  Open: https://${RPC_HOST}:6880"
echo "  aria2 RPC: wss://${RPC_HOST}:${RPC_PORT}/jsonrpc"
echo "  Secret: ${RPC_SECRET:0:16}..."
echo ""

exec nginx -g "daemon off;"
