#!/bin/sh
################################################################################
# slskd Init Script - Auto-configure API key on startup
################################################################################

set -eu

CONFIG_DIR="/app"
CONFIG_FILE="$CONFIG_DIR/slskd.yml"
SLSKD_SOULSEEK_USERNAME="${SLSKD_SOULSEEK_USERNAME:-}"
SLSKD_SOULSEEK_PASSWORD="${SLSKD_SOULSEEK_PASSWORD:-}"
SLSKD_SHARED_DIR="${SLSKD_SHARED_DIR:-/var/slskd/shared}"

echo "Initializing slskd configuration..."

# Create config directory if missing
mkdir -p "$CONFIG_DIR"

# Read API key from shared volume
if [ -f "/keys/slskd-api-key" ]; then
	SLSKD_API_KEY=$(cat /keys/slskd-api-key)
	echo "✓ Loaded slskd API key from shared volume"
else
	echo "⚠ Warning: API key not found at /keys/slskd-api-key"
	echo "Generating temporary key..."
	SLSKD_API_KEY=$(openssl rand -base64 48 | tr -d '\n')
fi

export SLSKD_API_KEY

# Export Soulseek credentials from environment
if [ -n "$SLSKD_SOULSEEK_USERNAME" ]; then
	export SLSKD_SOULSEEK_USERNAME
	echo "✓ Using Soulseek username from environment"
fi

if [ -n "$SLSKD_SOULSEEK_PASSWORD" ]; then
	export SLSKD_SOULSEEK_PASSWORD
	echo "✓ Using Soulseek password from environment"
fi

# Update slskd.yml with Soulseek credentials if provided
if [ -f "$CONFIG_FILE" ] && [ -n "$SLSKD_SOULSEEK_USERNAME" ] && [ -n "$SLSKD_SOULSEEK_PASSWORD" ]; then
	# Check if soulseek username is already configured
	if ! grep -q "^\s*username: $SLSKD_SOULSEEK_USERNAME" "$CONFIG_FILE"; then
		echo "Updating Soulseek credentials in config..."
		# Backup
		cp "$CONFIG_FILE" "${CONFIG_FILE}.bak"

		# Remove old config and regenerate
		rm "$CONFIG_FILE"
		echo "✓ Regenerating config with updated credentials"
	fi
fi

# Configure shared directories for Soulseek sharing
# Map container paths to host paths: /var/slskd/shared -> /mnt/storage/slskd-shared
export SLSKD_SHARED_DIR
echo "✓ Shared directory configured: $SLSKD_SHARED_DIR"

# Create slskd.yml if it doesn't exist or update API key
if [ ! -f "$CONFIG_FILE" ]; then
	echo "Creating new slskd configuration with API key..."
	cat >"$CONFIG_FILE" <<EOF
# slskd Configuration
# Auto-generated by init script

soulseek:
  username: ${SLSKD_SOULSEEK_USERNAME:-~}
  password: ${SLSKD_SOULSEEK_PASSWORD:-~}

directories:
  incomplete: /var/slskd/incomplete
  downloads: /var/slskd/shared

shares:
  directories:
    # Share music and audiobook libraries
    - /music
    - /audiobooks
    - /var/slskd/shared

web:
  authentication:
    api_keys:
      homarr:
        key: $SLSKD_API_KEY
        role: readonly
        cidr: 0.0.0.0/0,::/0
EOF
	echo "✓ slskd configuration created with API key and media shares"
elif ! grep -q "api_keys:" "$CONFIG_FILE"; then
	echo "Adding API key to existing config..."
	# Backup
	cp "$CONFIG_FILE" "${CONFIG_FILE}.bak"

	# Add API keys section if missing
	cat >>"$CONFIG_FILE" <<EOF

web:
  authentication:
    api_keys:
      homarr:
        key: $SLSKD_API_KEY
        role: readonly
        cidr: 0.0.0.0/0,::/0
EOF
	echo "✓ API key added to existing configuration"
fi

# Ensure shares are configured (add if missing)
if [ -f "$CONFIG_FILE" ] && ! grep -q "^shares:" "$CONFIG_FILE"; then
	echo "Adding shares configuration..."
	cp "$CONFIG_FILE" "${CONFIG_FILE}.bak"

	# Insert shares section after directories section
	sed -i '/^directories:/,/^web:/{
		/^web:/i\
shares:\
  directories:\
    - /var/slskd/shared
	}' "$CONFIG_FILE"

	echo "✓ Shares configuration added"
fi

# Continue with normal startup
exec /usr/bin/tini -- ./start.sh "$@"
