#!/bin/sh
################################################################################
# slskd Init Script - Auto-configure API key on startup
################################################################################

set -eu

CONFIG_DIR="/app"
CONFIG_FILE="$CONFIG_DIR/slskd.yml"
SLSKD_SOULSEEK_USERNAME="${SLSKD_SOULSEEK_USERNAME:-}"
SLSKD_SOULSEEK_PASSWORD="${SLSKD_SOULSEEK_PASSWORD:-}"
SLSKD_SHARED_DIR="${SLSKD_SHARED_DIR:-/var/slskd/shared}"
SLSKD_UPLOAD_SLOTS="${SLSKD_UPLOAD_SLOTS:-4}"
SLSKD_UPLOAD_SPEED_LIMIT="${SLSKD_UPLOAD_SPEED_LIMIT:-25}"
SLSKD_DOWNLOAD_SLOTS="${SLSKD_DOWNLOAD_SLOTS:-500}"
SLSKD_DOWNLOAD_SPEED_LIMIT="${SLSKD_DOWNLOAD_SPEED_LIMIT:-1000}"
SLSKD_QUEUE_FILES="${SLSKD_QUEUE_FILES:-500}"
SLSKD_QUEUE_MEGABYTES="${SLSKD_QUEUE_MEGABYTES:-5000}"
SLSKD_GROUP_UPLOAD_SLOTS="${SLSKD_GROUP_UPLOAD_SLOTS:-4}"
SLSKD_GROUP_UPLOAD_SPEED_LIMIT="${SLSKD_GROUP_UPLOAD_SPEED_LIMIT:-${SLSKD_UPLOAD_SPEED_LIMIT}}"
SLSKD_GROUP_QUEUE_FILES="${SLSKD_GROUP_QUEUE_FILES:-150}"
SLSKD_GROUP_QUEUE_MEGABYTES="${SLSKD_GROUP_QUEUE_MEGABYTES:-1500}"
SLSKD_LOGGER_DISK="${SLSKD_LOGGER_DISK:-true}"
SLSKD_LOGGER_NO_COLOR="${SLSKD_LOGGER_NO_COLOR:-true}"
SLSKD_LOGGER_LOKI="${SLSKD_LOGGER_LOKI:-null}"
SLSKD_METRICS_ENABLED="${SLSKD_METRICS_ENABLED:-${SLSKD_METRICS:-false}}"
SLSKD_METRICS_URL="${SLSKD_METRICS_URL:-/metrics}"
SLSKD_METRICS_AUTH_DISABLED="${SLSKD_METRICS_AUTH_DISABLED:-true}"
SLSKD_METRICS_USERNAME="${SLSKD_METRICS_USERNAME:-slskd}"
SLSKD_METRICS_PASSWORD="${SLSKD_METRICS_PASSWORD:-slskd}"

echo "Initializing slskd configuration..."

# Create config directory if missing
mkdir -p "$CONFIG_DIR"

# Read API key from shared volume
if [ -f "/keys/slskd-api-key" ]; then
	SLSKD_API_KEY=$(cat /keys/slskd-api-key)
	echo "✓ Loaded slskd API key from shared volume"
else
	echo "⚠ Warning: API key not found at /keys/slskd-api-key"
	echo "Generating temporary key..."
	SLSKD_API_KEY=$(openssl rand -base64 48 | tr -d '\n')
fi

export SLSKD_API_KEY

# Export Soulseek credentials from environment
if [ -n "$SLSKD_SOULSEEK_USERNAME" ]; then
	export SLSKD_SOULSEEK_USERNAME
	echo "✓ Using Soulseek username from environment"
fi

if [ -n "$SLSKD_SOULSEEK_PASSWORD" ]; then
	export SLSKD_SOULSEEK_PASSWORD
	echo "✓ Using Soulseek password from environment"
fi

# Update slskd.yml with Soulseek credentials if provided
if [ -f "$CONFIG_FILE" ] && [ -n "$SLSKD_SOULSEEK_USERNAME" ] && [ -n "$SLSKD_SOULSEEK_PASSWORD" ]; then
	# Check if soulseek username is already configured
	if ! grep -q "^\s*username: $SLSKD_SOULSEEK_USERNAME" "$CONFIG_FILE"; then
		echo "Updating Soulseek credentials in config..."
		# Backup
		cp "$CONFIG_FILE" "${CONFIG_FILE}.bak"

		# Remove old config and regenerate
		rm "$CONFIG_FILE"
		echo "✓ Regenerating config with updated credentials"
	fi
fi

# Configure shared directories for Soulseek sharing
# Map container paths to host paths: /var/slskd/shared -> /mnt/storage/slskd-shared
export SLSKD_SHARED_DIR
echo "✓ Shared directory configured: $SLSKD_SHARED_DIR"

# Create slskd.yml if it doesn't exist or update API key
if [ ! -f "$CONFIG_FILE" ]; then
	echo "Creating new slskd configuration with API key..."
	cat >"$CONFIG_FILE" <<EOF
# slskd Configuration
# Auto-generated by init script

soulseek:
  username: ${SLSKD_SOULSEEK_USERNAME:-~}
  password: ${SLSKD_SOULSEEK_PASSWORD:-~}

directories:
  incomplete: /var/slskd/incomplete
  downloads: /var/slskd/downloads

shares:
  storage_mode: disk
  directories:
    # Share all mounted media libraries
    - /music
    - /audiobooks
    - /var/slskd/shared
  filters:
    # Exclude common non-music files
    - '\.jpg$'
    - '\.jpeg$'
    - '\.png$'
    - '\.gif$'
    - '\.nfo$'
    - '\.txt$'
    - '\.log$'

global:
  upload:
    slots: ${SLSKD_UPLOAD_SLOTS}
    speed_limit: ${SLSKD_UPLOAD_SPEED_LIMIT}
  limits:
    queued:
      files: ${SLSKD_QUEUE_FILES}
      megabytes: ${SLSKD_QUEUE_MEGABYTES}
  download:
    slots: ${SLSKD_DOWNLOAD_SLOTS}
    speed_limit: ${SLSKD_DOWNLOAD_SPEED_LIMIT}

groups:
  default:
    upload:
      slots: ${SLSKD_GROUP_UPLOAD_SLOTS}
      speed_limit: ${SLSKD_GROUP_UPLOAD_SPEED_LIMIT}
    limits:
      queued:
        files: ${SLSKD_GROUP_QUEUE_FILES}
        megabytes: ${SLSKD_GROUP_QUEUE_MEGABYTES}

logger:
  disk: ${SLSKD_LOGGER_DISK}
  no_color: ${SLSKD_LOGGER_NO_COLOR}
  loki: ${SLSKD_LOGGER_LOKI}

metrics:
  enabled: ${SLSKD_METRICS_ENABLED}
  url: ${SLSKD_METRICS_URL}
  authentication:
    disabled: ${SLSKD_METRICS_AUTH_DISABLED}
    username: ${SLSKD_METRICS_USERNAME}
    password: ${SLSKD_METRICS_PASSWORD}

web:
  authentication:
    api_keys:
      homarr:
        key: $SLSKD_API_KEY
        role: readonly
        cidr: 0.0.0.0/0,::/0
EOF
	echo "✓ slskd configuration created with API key and media shares"
elif ! grep -q "api_keys:" "$CONFIG_FILE"; then
	echo "Adding API key to existing config..."
	# Backup
	cp "$CONFIG_FILE" "${CONFIG_FILE}.bak"

	# Add API keys section if missing
	cat >>"$CONFIG_FILE" <<EOF

web:
  authentication:
    api_keys:
      homarr:
        key: $SLSKD_API_KEY
        role: readonly
        cidr: 0.0.0.0/0,::/0
EOF
	echo "✓ API key added to existing configuration"
fi

# Ensure transfer limits and queue settings exist
if [ -f "$CONFIG_FILE" ] && ! grep -q "^global:" "$CONFIG_FILE"; then
	echo "Adding global transfer limits and queue settings..."
	cat >>"$CONFIG_FILE" <<EOF

global:
  upload:
    slots: ${SLSKD_UPLOAD_SLOTS}
    speed_limit: ${SLSKD_UPLOAD_SPEED_LIMIT}
  limits:
    queued:
      files: ${SLSKD_QUEUE_FILES}
      megabytes: ${SLSKD_QUEUE_MEGABYTES}
  download:
    slots: ${SLSKD_DOWNLOAD_SLOTS}
    speed_limit: ${SLSKD_DOWNLOAD_SPEED_LIMIT}
EOF
	echo "✓ Global limits and queues added"
fi

if [ -f "$CONFIG_FILE" ] && ! grep -q "^groups:" "$CONFIG_FILE"; then
	echo "Adding default group transfer limits..."
	cat >>"$CONFIG_FILE" <<EOF

groups:
  default:
    upload:
      slots: ${SLSKD_GROUP_UPLOAD_SLOTS}
      speed_limit: ${SLSKD_GROUP_UPLOAD_SPEED_LIMIT}
    limits:
      queued:
        files: ${SLSKD_GROUP_QUEUE_FILES}
        megabytes: ${SLSKD_GROUP_QUEUE_MEGABYTES}
EOF
	echo "✓ Group limits added"
fi

# Ensure logger settings exist
if [ -f "$CONFIG_FILE" ] && ! grep -q "^logger:" "$CONFIG_FILE"; then
	echo "Adding logger configuration..."
	cat >>"$CONFIG_FILE" <<EOF

logger:
  disk: ${SLSKD_LOGGER_DISK}
  no_color: ${SLSKD_LOGGER_NO_COLOR}
  loki: ${SLSKD_LOGGER_LOKI}
EOF
	echo "✓ Logger configuration added"
fi

# Ensure metrics settings exist
if [ -f "$CONFIG_FILE" ] && ! grep -q "^metrics:" "$CONFIG_FILE"; then
	echo "Adding metrics configuration..."
	cat >>"$CONFIG_FILE" <<EOF

metrics:
  enabled: ${SLSKD_METRICS_ENABLED}
  url: ${SLSKD_METRICS_URL}
  authentication:
    disabled: ${SLSKD_METRICS_AUTH_DISABLED}
    username: ${SLSKD_METRICS_USERNAME}
    password: ${SLSKD_METRICS_PASSWORD}
EOF
	echo "✓ Metrics configuration added"
fi

# Ensure shares are configured (add if missing)
if [ -f "$CONFIG_FILE" ] && ! grep -q "^shares:" "$CONFIG_FILE"; then
	echo "Adding shares configuration..."
	cp "$CONFIG_FILE" "${CONFIG_FILE}.bak"

	# Append shares section at the end
	cat >>"$CONFIG_FILE" <<'SHARESEOF'

shares:
  directories:
    - /music
    - /audiobooks
    - /var/slskd/shared
SHARESEOF

	echo "✓ Shares configuration added"
fi

# Force rescan of shares on each startup
echo "✓ slskd will rescan shares on startup"

# Continue with normal startup
exec /usr/bin/tini -- ./start.sh "$@"
