---
rules:
  no-unbound-port-interfaces: 0
  services-alphabetical-order: 0
  require-quotes-in-ports: 0
  top-level-properties-order: 0
  service-ports-alphabetical-order: 0
  service-keys-order: 0
  no-version-field: 0
