################################################################################
# Woodpecker CI/CD Pipeline - PotatoStack
# Deploys stack updates on git tags
################################################################################

when:
  event: tag

steps:
  validate:
    image: docker:24
    commands:
      - cd /stack && docker compose config --quiet
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/daniel/potatostack:/stack

  deploy:
    image: docker:24
    commands:
      - cd /stack && docker compose pull
      - cd /stack && docker compose up -d --remove-orphans
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/daniel/potatostack:/stack
    depends_on:
      - validate

  cleanup:
    image: docker:24
    commands:
      - docker image prune -f --filter "until=168h"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - deploy
