# Staging Environment Overrides
# Usage: docker compose -f docker-compose.yml -f compose.staging.yml up -d
#
# Staging mirrors production but with:
# - Debug logging enabled
# - Relaxed resource limits for testing
# - Additional debug tools
# - Test data seeding allowed

services:
  # Monitoring Stack - Staging Configuration
  grafana:
    restart: unless-stopped
    environment:
      - GF_SERVER_ROOT_URL=https://grafana-staging.yourdomain.com
      - GF_SECURITY_ADMIN_PASSWORD=${GF_ADMIN_PASSWORD:-admin}
      - GF_ANALYTICS_REPORTING_ENABLED=false
      - GF_LOG_LEVEL=debug
      - GF_USERS_ALLOW_SIGN_UP=true
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 768M

  prometheus:
    restart: unless-stopped
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=7d"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
      - "--web.enable-lifecycle"
      - "--web.enable-admin-api"
      - "--log.level=debug"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: 1536M

  loki:
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"
    deploy:
      resources:
        limits:
          cpus: "0.75"
          memory: 768M

  # Database Services - Staging with Debug
  postgres:
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-stagingpass}
      - POSTGRES_DB=${POSTGRES_DB:-staging}
    command:
      - "postgres"
      - "-c"
      - "shared_buffers=128MB"
      - "-c"
      - "max_connections=100"
      - "-c"
      - "log_statement=all"
      - "-c"
      - "log_min_duration_statement=100"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1G

  redis:
    restart: unless-stopped
    command: >
      redis-server
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru
      --save 60 1000
      --requirepass ${REDIS_PASSWORD:-stagingredis}
      --loglevel debug
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M

  # Reverse Proxy - Staging with Dashboard
  traefik:
    restart: unless-stopped
    command:
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--log.level=DEBUG"
      - "--accesslog=true"
      - "--metrics.prometheus=true"
    ports:
      - "8080:8080"
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"

  # Application Services - Staging Configuration
  vaultwarden:
    restart: unless-stopped
    environment:
      - SIGNUPS_ALLOWED=true
      - INVITATIONS_ALLOWED=true
      - ADMIN_TOKEN=${VAULTWARDEN_ADMIN_TOKEN:-staging-admin-token}
      - DOMAIN=https://vault-staging.yourdomain.com
      - LOG_LEVEL=debug
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"

  # Additional Staging Tools
  adminer:
    image: adminer:latest
    restart: unless-stopped
    ports:
      - "8081:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
      - ADMINER_DESIGN=pepa-linha
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 128M

  # Redis Commander for debugging
  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: unless-stopped
    ports:
      - "8082:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379:0:${REDIS_PASSWORD:-stagingredis}
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 128M

# Staging Networks
networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-staging

# Staging Volumes - Local bind mounts for easy inspection
volumes:
  postgres_data:
    driver: local

  prometheus_data:
    driver: local

  grafana_data:
    driver: local
