# Light Stack - Development Environment Overrides
# Usage: docker compose -f docker-compose.yml -f compose.development.yml up -d
#
# Development features for light stack

services:
  # Monitoring - Development
  grafana:
    restart: "no"
    environment:
      - GF_SERVER_ROOT_URL=http://localhost:3002
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_LOG_LEVEL=debug
    ports:
      - "3002:3000"
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "1"

  prometheus:
    restart: "no"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=1d"
      - "--web.enable-lifecycle"
      - "--log.level=debug"
    ports:
      - "9090:9090"
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "1"

  # Database - Development
  postgres:
    restart: "no"
    environment:
      - POSTGRES_PASSWORD=dev
      - POSTGRES_DB=dev
      - POSTGRES_USER=dev
    command:
      - "postgres"
      - "-c"
      - "log_statement=all"
    ports:
      - "5432:5432"
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "1"

  redis:
    restart: "no"
    command: >
      redis-server
      --maxmemory 64mb
      --save ""
      --appendonly no
      --loglevel debug
    ports:
      - "6379:6379"
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "1"

  # Traefik - Development
  traefik:
    restart: "no"
    command:
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=true"
      - "--entrypoints.web.address=:80"
      - "--log.level=DEBUG"
    ports:
      - "80:80"
      - "8080:8080"
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "1"

  # Applications - Development
  vaultwarden:
    restart: "no"
    environment:
      - SIGNUPS_ALLOWED=true
      - ADMIN_TOKEN=dev-token
      - LOG_LEVEL=trace
    ports:
      - "8000:80"
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "1"

  freshrss:
    restart: "no"
    ports:
      - "8001:80"
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "1"

  # Development Tools
  adminer:
    image: adminer:latest
    restart: "no"
    ports:
      - "8081:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=postgres

  mailhog:
    image: mailhog/mailhog:latest
    restart: "no"
    ports:
      - "1025:1025"
      - "8025:8025"
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "1"

networks:
  default:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  prometheus_data:
    driver: local
  grafana_data:
    driver: local
