# Light Stack - Staging Environment Overrides
# Usage: docker compose -f docker-compose.yml -f compose.staging.yml up -d
#
# Staging configuration for testing with debug features

services:
  # Monitoring - Staging
  grafana:
    restart: unless-stopped
    environment:
      - GF_SERVER_ROOT_URL=https://grafana-staging.yourdomain.com
      - GF_SECURITY_ADMIN_PASSWORD=${GF_ADMIN_PASSWORD:-admin}
      - GF_LOG_LEVEL=debug
      - GF_USERS_ALLOW_SIGN_UP=true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M

  prometheus:
    restart: unless-stopped
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=3d"
      - "--web.enable-lifecycle"
      - "--log.level=debug"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M

  # Database - Staging
  postgres:
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-stagingpass}
    command:
      - "postgres"
      - "-c"
      - "log_statement=all"
      - "-c"
      - "log_min_duration_statement=100"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    restart: unless-stopped
    command: >
      redis-server
      --maxmemory 128mb
      --maxmemory-policy allkeys-lru
      --requirepass ${REDIS_PASSWORD:-stagingredis}
      --loglevel debug
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"

  # Traefik - Staging with Dashboard
  traefik:
    restart: unless-stopped
    command:
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--log.level=DEBUG"
    ports:
      - "8080:8080"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"

  # Applications - Staging
  vaultwarden:
    restart: unless-stopped
    environment:
      - SIGNUPS_ALLOWED=true
      - ADMIN_TOKEN=${VAULTWARDEN_ADMIN_TOKEN:-staging-token}
      - LOG_LEVEL=debug
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"

  # Debug Tools
  adminer:
    image: adminer:latest
    restart: unless-stopped
    ports:
      - "8081:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 64M

networks:
  default:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  prometheus_data:
    driver: local
  grafana_data:
    driver: local
