#!/bin/sh
################################################################################
# slskd Init Script - Auto-configure API key on startup
################################################################################

CONFIG_DIR="/app"
CONFIG_FILE="$CONFIG_DIR/slskd.yml"

echo "Initializing slskd configuration..."

# Create config directory if missing
mkdir -p "$CONFIG_DIR"

# Read API key from shared volume
if [ -f "/keys/slskd-api-key" ]; then
    SLSKD_API_KEY=$(cat /keys/slskd-api-key)
    echo "✓ Loaded slskd API key from shared volume"
else
    echo "⚠ Warning: API key not found at /keys/slskd-api-key"
    echo "Generating temporary key..."
    SLSKD_API_KEY=$(openssl rand -base64 48 | tr -d '\n')
fi

export SLSKD_API_KEY

# Create slskd.yml if it doesn't exist or update API key
if [ ! -f "$CONFIG_FILE" ]; then
    echo "Creating new slskd configuration with API key..."
    cat > "$CONFIG_FILE" <<EOF
# slskd Configuration
# Auto-generated by init script

web:
  authentication:
    api_keys:
      homepage:
        key: $SLSKD_API_KEY
        role: readonly
        cidr: 0.0.0.0/0,::/0
EOF
    echo "✓ slskd configuration created with API key"
elif ! grep -q "api_keys:" "$CONFIG_FILE"; then
    echo "Adding API key to existing config..."
    # Backup
    cp "$CONFIG_FILE" "${CONFIG_FILE}.bak"

    # Add API keys section if missing
    cat >> "$CONFIG_FILE" <<EOF

web:
  authentication:
    api_keys:
      homepage:
        key: $SLSKD_API_KEY
        role: readonly
        cidr: 0.0.0.0/0,::/0
EOF
    echo "✓ API key added to existing configuration"
fi

# Continue with normal startup
exec /slskd "$@"
