#!/bin/sh
################################################################################
# slskd Init Script - Auto-configure API key on startup
################################################################################

CONFIG_DIR="/app"
CONFIG_FILE="$CONFIG_DIR/slskd.yml"

echo "Initializing slskd configuration..."

# Create config directory if missing
mkdir -p "$CONFIG_DIR"

# Read API key from shared volume
if [ -f "/keys/slskd-api-key" ]; then
	SLSKD_API_KEY=$(cat /keys/slskd-api-key)
	echo "✓ Loaded slskd API key from shared volume"
else
	echo "⚠ Warning: API key not found at /keys/slskd-api-key"
	echo "Generating temporary key..."
	SLSKD_API_KEY=$(openssl rand -base64 48 | tr -d '\n')
fi

export SLSKD_API_KEY

# Export Soulseek credentials from environment
if [ -n "$SLSKD_SOULSEEK_USERNAME" ]; then
	export SLSKD_SOULSEEK_USERNAME
	echo "✓ Using Soulseek username from environment"
fi

if [ -n "$SLSKD_SOULSEEK_PASSWORD" ]; then
	export SLSKD_SOULSEEK_PASSWORD
	echo "✓ Using Soulseek password from environment"
fi

# Update slskd.yml with Soulseek credentials if provided
if [ -f "$CONFIG_FILE" ] && [ -n "$SLSKD_SOULSEEK_USERNAME" ] && [ -n "$SLSKD_SOULSEEK_PASSWORD" ]; then
	echo "Updating Soulseek credentials in config..."
	# Check if soulseek section exists (commented or not)
	if grep -q '# soulseek:' "$CONFIG_FILE"; then
		# Uncomment and update the soulseek section
		sed -i 's/# soulseek:/soulseek:/' "$CONFIG_FILE"
		sed -i 's/#   address:/  address:/' "$CONFIG_FILE"
		sed -i 's/#   port:/  port:/' "$CONFIG_FILE"
		sed -i "s/#   username: ~/  username: $SLSKD_SOULSEEK_USERNAME/" "$CONFIG_FILE"
		sed -i "s/#   password: ~/  password: $SLSKD_SOULSEEK_PASSWORD/" "$CONFIG_FILE"
		echo "✓ Soulseek credentials configured"
	fi
fi

# Create slskd.yml if it doesn't exist or update API key
if [ ! -f "$CONFIG_FILE" ]; then
	echo "Creating new slskd configuration with API key..."
	cat >"$CONFIG_FILE" <<EOF
# slskd Configuration
# Auto-generated by init script

soulseek:
  username: ${SLSKD_SOULSEEK_USERNAME:-~}
  password: ${SLSKD_SOULSEEK_PASSWORD:-~}

directories:
  incomplete: /var/slskd/incomplete
  downloads: /var/slskd/shared

web:
  authentication:
    api_keys:
      homepage:
        key: $SLSKD_API_KEY
        role: readonly
        cidr: 0.0.0.0/0,::/0
EOF
	echo "✓ slskd configuration created with API key"
elif ! grep -q "api_keys:" "$CONFIG_FILE"; then
	echo "Adding API key to existing config..."
	# Backup
	cp "$CONFIG_FILE" "${CONFIG_FILE}.bak"

	# Add API keys section if missing
	cat >>"$CONFIG_FILE" <<EOF

web:
  authentication:
    api_keys:
      homepage:
        key: $SLSKD_API_KEY
        role: readonly
        cidr: 0.0.0.0/0,::/0
EOF
	echo "✓ API key added to existing configuration"
fi

# Add directories config if missing
if ! grep -q "^directories:" "$CONFIG_FILE"; then
	echo "Adding directories configuration..."
	sed -i "/^soulseek:/a\\
\\
directories:\\
  incomplete: /var/slskd/incomplete\\
  downloads: /var/slskd/shared" "$CONFIG_FILE"
	echo "✓ Directories configured: incomplete -> /var/slskd/incomplete, downloads -> /var/slskd/shared"
fi

# Continue with normal startup
exec /usr/bin/tini -- ./start.sh "$@"
